import '../../../../public/styles/bootstrap.min.css'
import '../../../../public/styles/font-awesome.min.css'
import '../../../../public/styles/animate.min.css'
import '../../../../public/styles/react-select.min.css'
import '../../../../public/styles/react-datetime.css'
import '../../../../public/styles/basic.min.css'
import '../../../../public/styles/dropzone.min.css'
import '../../../../public/styles/sweetalert.css'
import '../../../../public/styles/style.css'
import '../../../../public/styles/rangeInput.css'
import '../../../../public/styles/reactTagsInput.css'
import '../../../../public/styles/google-map-react.css'
import '../../../../public/styles/content-overlay.css'
import '../../../../public/styles/hover-edit.css'
import '../../../../public/styles/custom-icons.css'
import '../../../../public/styles/custom.css'

